version: '3.0'

services:
  db:
    image: mysql:8.0.25
    restart: always
    ports:
      - 3301:3306
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: 12345
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: user_authentication